from django.shortcuts import render
from django.http import HttpResponse
import random
# Create your views here.

# Créer une fonction pour render fortune.html


fortuneList = [
    "All will go well with your new project.",
    "If you continually give, you will continually have.",
    "Self-knowledge is a life long process.",
    "You are busy, but you are happy.",
    "Your abilities are unparalleled.",
    "Those who care will make the effort.",
    "Now is the time to try something new.",
    "Miles are covered one step at a time.",
    "Don’t just think, act!",
    "Opportunities don't happen. You create them.",
    "The only limit to our realization of tomorrow is our doubts of today.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Believe in yourself and all that you are.",
    "Success is not the key to happiness. Happiness is the key to success.",
    "Life is 10% what happens to us and 90% how we react to it.",
    "You will find great joy in the near future.",
    "Your positive attitude will bring you much success.",
    "You have a unique and special talent.",
    "A beautiful, smart, and loving person will be coming into your life.",
    "Your hard work will soon pay off.",
    "Good things are coming your way.",
    "Expect great things from yourself.",
    "Your talents will be recognized and rewarded.",
    "You will achieve your goals.",
    "Happiness is found within yourself.",
    "You will soon receive some good news.",
    "An unexpected event will bring you joy.",
    "You will overcome challenges with grace.",
    "Your dreams are within reach.",
    "You are capable of amazing things.",
    "A thrilling time is in your immediate future.",
    "You will be surrounded by love and support.",
    "An exciting opportunity is on the horizon.",
    "You will make new friends soon.",
    "You will discover a hidden talent.",
    "A fresh start will improve your situation.",
    "A pleasant surprise is waiting for you.",
    "You will achieve a long-held goal.",
    "You are on the right path.",
    "Your efforts will be rewarded.",
    "New opportunities will present themselves.",
    "You will make a significant impact.",
    "You are loved more than you know.",
    "You will soon have a chance to show your abilities.",
    "Your creativity will lead to success.",
    "A new adventure is about to begin.",
    "You will find success in unexpected places.",
    "You will soon receive recognition for your efforts.",
    "Your positive energy will attract good things.",
    "You are destined for greatness.",
    "Good fortune will come your way.",
    "You will soon meet someone who will inspire you.",
    "Your kindness will be repaid.",
    "You will find peace and contentment.",
    "Your hard work is about to pay off.",
    "You are a source of inspiration to others.",
    "A new opportunity will bring you excitement.",
    "You will soon be in the spotlight.",
    "A new relationship will bring you joy.",
    "You will achieve a personal milestone.",
    "Your passion will lead to success.",
    "You will soon receive a compliment.",
    "A positive change is on the way.",
    "You will find success in your endeavors.",
    "Your dedication will be rewarded.",
    "A new chapter in your life is about to begin.",
    "You will soon discover a new passion.",
    "You will receive good news soon.",
    "Your future is looking bright.",
    "You will achieve balance in your life.",
    "Your perseverance will pay off.",
    "You will find joy in the little things.",
    "Your efforts will be recognized.",
    "A new journey will bring you fulfillment.",
    "You will soon overcome a challenge.",
    "Your positive outlook will bring you success.",
    "You will find happiness in your work.",
    "A rewarding experience is on the way.",
    "You will soon achieve a long-term goal.",
    "You will find success in your personal life.",
    "Your confidence will lead to great achievements.",
    "You will soon be rewarded for your efforts.",
    "Your hard work will soon bear fruit.",
    "You will discover new opportunities.",
    "A joyful event is in your future.",
    "Your enthusiasm will lead to success.",
    "You will make a valuable connection soon.",
    "Your dreams will soon become reality.",
    "You will soon experience a breakthrough.",
    "Your positive attitude will attract success.",
    "You will find new avenues for growth.",
    "Your efforts will be recognized and appreciated.",
    "You will soon experience a burst of creativity.",
    "A happy event is on the horizon.",
    "You will find fulfillment in your endeavors.",
    "Your dedication will lead to success.",
    "You will soon be rewarded for your hard work.",
    "A positive change is coming your way.",
    "You will find success in your career.",
    "Your determination will lead to great achievements.",
    "You will soon receive an opportunity to shine.",
    "Your creative ideas will be well received.",
    "You will find joy in the journey ahead.",
    "Your optimism will lead to great results.",
    "You will soon make a meaningful impact.",
    "Your hard work will soon pay off.",
    "You will achieve success through perseverance.",
    "A new opportunity will bring you excitement.",
    "You will soon experience a surge of energy.",
    "Your dedication will lead to great things.",
    "You will find new sources of inspiration.",
    "A rewarding experience is on the horizon.",
    "You will soon reach a significant milestone.",
    "Your positive attitude will bring you success.",
    "You will find fulfillment in your personal life.",
    "Your creativity will open new doors.",
    "A new adventure will bring you joy.",
    "You will soon see the fruits of your labor.",
    "Your hard work will be recognized and rewarded.",
    "You will find success in your current endeavors.",
    "A positive development is on the way.",
    "You will soon achieve a long-held dream.",
    "Your enthusiasm will lead to new opportunities.",
    "You will find success through your perseverance.",
    "A happy surprise is in your future.",
    "Your positive outlook will attract success.",
    "You will soon be recognized for your efforts.",
    "Your dedication will bring you great rewards.",
    "A new opportunity will bring you excitement.",
    "You will find joy in your achievements.",
    "Your hard work will soon bear fruit.",
    "You will soon receive an unexpected gift.",
    "Your creativity will lead to new possibilities.",
    "A rewarding experience is just around the corner.",
    "You will soon experience a burst of inspiration.",
    "Your positive attitude will lead to success.",
    "You will find fulfillment in your work.",
    "A new chapter in your life will bring joy.",
    "Your hard work will soon be recognized.",
    "You will achieve your goals with perseverance.",
    "A positive change is on the horizon.",
    "You will soon find new sources of inspiration."
]


def fortune(request):
    fortune = random.choice(fortuneList)
    context = { "fortune": fortune}
    return render (request, "getacookie/fortune.html",context)


